### ISSUE TITLE
maintain RVInfo after clone a basic block before the linearization pass

### ISSUE THREAD

**Issue by HuihuiSun** [cdl-saarland/rv#18]
I come across with std::out_of_range error at Linearizer pass for bitfield application. It crashs at verifyBlockIndex(). I assume that buildBlockIndex() build some blockindex info and verfifyBlockIndex() does the work for verifying the correctness of this building.  
Besides, I also think I may lose something when maintaining the RV-related vecInfo or Domtree updating for the cloned basic block. I have done clone the basic block, remap the instructions with ValueMap,updating phi nodes with successor phis. What may be missing?

**Comment by simoll** [comment]
I need some context to understand what you are trying to do here.
At what point do you clone the block? In what way is it attached to the Control-Flow Graph, and the analyses (DT, PDT, LI)? What kind of updates do you perform on vecInfo? Can you provide a stack trace and an BC file with the modified CFG before the crash?

**Comment by HuihuiSun** [comment]
I will send you an email with detailed information. It is a bit hard to layout the information here, because attached file is not allowed.

**Comment by simoll** [comment]
This turned out to be unrelated to RV
