### ISSUE TITLE
Build RV as a LLVM plugin

### ISSUE THREAD

**Issue by vchuravy** [cdl-saarland/rv#47]
I was thinking about how best to deploy RV for my usecase and I am curious if anyone has tried building RV as an LLVM/opt plugin.

We link against the LLVM dylib and being able to dlopen and then add the RV passes would greatly simplify the deployment for us.

**Comment by NigelYYB** [comment]
I have a similar question here. The readme docs says one could just `Invoke clang with -fplugin=libRV.so -mllvm -rv-loopve` to use the out loop vectorizer. I tested this using llvm 10 + RV_release/10.x and I got an error msg 

```
clang (LLVM option parsing): Unknown command line argument '-rv-loopvec'.
```

Besides, the library name I have is `LLVMRV.so` instead of `libRV.so`. 

Has anyone tried this plugin mode?

**Comment by simoll** [comment]
That's available in the NEC version (hpce/develop branch): https://github.com/sx-aurora-dev/rv/commit/ff98942b295ff96d3cfcb2205fb6b52d2e3ccea3
I'll pick the patch onto master.

**Comment by simoll** [comment]
Fixed by 86ffc07

**Comment by NigelYYB** [comment]
I might have missed something. I got a `LLVMRV.so` instead of `libRV.so`, is this expected?

Also, with this commit, I can't do `opt -load <path_to_lib>/LLVMRV.so -rv helloworld.ll` because it doesn't recognize the `-rv` option. Are we missing the `static RegisterPass<PassName>` in all the passes?

**Comment by simoll** [comment]
> I might have missed something. I got a `LLVMRV.so` instead of `libRV.so`, is this expected?
> 
> Also, with this commit, I can't do `opt -load <path_to_lib>/LLVMRV.so -rv helloworld.ll` because it doesn't recognize the `-rv` option. This is the same for `clang++ -O3 -fplugin=<path_to_lib>/LLVMRV.so -mllvm -rv helloworld.cpp`. I'm new to LLVM pass managers and plugins.. The `registerRVPasses` wasn't invoked in my case.. Are we missing the `static RegisterPass<PassName>` in all the passes or some other magic parts?
> 
> Thanks~

There should still be a `libRV.so` if there was one before. What's your build configuration (cmake args)?

**Comment by NigelYYB** [comment]
Actually I've got 2 files `LLVMRV.so and libRV.a` using the following cmake args along with other LLVM cmake args.
The `rv` folder is at `llvm-project/rv` along side the llvm and clang folder.

```
             -DLLVM_EXTERNAL_PROJECTS="rv" \
             -DLLVM_EXTERNAL_RV_SOURCE_DIR=../rv \
             -DRV_ENABLE_CRT=on \
             -DRV_ENABLE_SLEEF=on \
             -DRV_ENABLE_ADVSIMD=on \
```

I could manually convert `libRV.a` to a `.so` file, tho.
