### ISSUE TITLE
SCEVCastExpr has been renamed to SCEVIntegralCastExpr

### ISSUE THREAD

**Issue by Kazhuu** [cdl-saarland/rv#51]
When compiling with latest master LLVM following error message is printed
```
/home/kazooie/extra/programming/llvm-project/rv/src/native/MemoryAccessGrouper.cpp:198:27: error: ‘SCEVCastExpr’ was not declared in this scope
  198 |       auto * aCast = cast<SCEVCastExpr>(A);
      |                           ^~~~~~~~~~~~
/home/kazooie/extra/programming/llvm-project/rv/src/native/MemoryAccessGrouper.cpp:198:42: error: no matching function for call to ‘cast<<expression error> >(const llvm::SCEV*&)’
  198 |       auto * aCast = cast<SCEVCastExpr>(A);
      |                                          ^
```
It seems to relate to this change: https://reviews.llvm.org/D89455. Is PR welcome?
I also noticed that experimental intrinsics have been renamed not to include experimental_* anymore: https://reviews.llvm.org/rG322d0afd875

**Comment by simoll** [comment]
We track LLVM upstream loosely - the LLVM upstream state at the time of the last RV commit usually works (we should find a better way to sync with LLVM though). A PR to fix these new issues is very welcome! :)

**Comment by simoll** [comment]
This issue was fixed in https://github.com/cdl-saarland/rv/pull/52
