### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by madmann91** [cdl-saarland/rv#6]
During build, RV emits an empty error message:

```
...
  store float %480, float* %483 : varying
  store float %479, float* %482 : varying
  ret void : uni

}
RV: error: 

^
Extracting a scalar value from a vector:
Original Value:   %366 = fmul float %340, %inv_det
Vector Value:   %183 = fmul <8 x float> %157, %inv_det_SIMD
...
```

Compilation works nevertheless, and LLVM IR files are correctly generated. The bug can be triggered by building [rodent](https://github.com/madmann91/rodent) on the `master` branch.

**Comment by simoll** [comment]
smDiag was always printed to errs(). Will now only happen if no module was created.
