### ISSUE TITLE
Attributes.inc: No such file or directory

### ISSUE THREAD

**Issue by ssinad** [cdl-saarland/rv#62]
I tried to build llvm-project with rv inside by adding the options to the `cmake` command (`-DLLVM_EXTERNAL_PROJECTS="rv" -DLLVM_EXTERNAL_RV_SOURCE_DIR=llvm-project/rv`). However, I got the following error multiple times:
```
llvm-project/llvm/include/llvm/IR/Attributes.h:88:14 fatal error: llvm/IR/Attributes.inc: No such file or directory
```
I checked and it seems that `Attributes.inc` hasn't been generated yet.  
Is there a way to fix this?

**Comment by richardmembarth** [comment]
This error seems to be related to building LLVM, not RV?

**Comment by richardmembarth** [comment]
It's hard to tell without any log ...

The current master branch is stuck at LLVM 14, the `release/14.x` branch is more up-to-date.
You can find a script that builds also LLVM + RV here: https://github.com/AnyDSL/anydsl/

**Comment by richardmembarth** [comment]
Since there is no update, I assume that you could build RV.
