### ISSUE TITLE
DFGBase specializations in different namespaces

### ISSUE THREAD

**Issue by pacxx** [cdl-saarland/rv#8]
I recently updated RV to the latest commit and the following errors occurred: 

```
llvm/tools/rv/src/analysis/DFG.cpp:11:53: error: specialization of ‘template<bool backward> bool llvm::DFGBaseWrapper<backward>::runOnFunction(llvm::Function&)’ in different namespace [-fpermissive]
 bool DFGBaseWrapper<true>::runOnFunction(Function& F)

...
```

I reverted our custom port to LLVM 6.0 since I got a linker error and the original code is now compatible with the LLVM 6.0 API. 

The compile error can be fixed in DFG.cpp by pulling everything into the llvm namespace. However, I was wondering if DFGBase should realy live in the llvm namespace.

**Comment by simoll** [comment]
fixed by fee2427
